name: Release

on:
  push:
    branches:
      - main
      - node-migration

jobs:
  path-filter:
    name: Check Path Changes
    runs-on: ubuntu-latest
    outputs:
      bot: ${ steps.changes.outputs.bot }
      gateway: ${ steps.changes.outputs.gateway }
      rest: ${ steps.changes.outputs.rest }
      types: ${ steps.changes.outputs.types }
      utils: ${ steps.changes.outputs.utils }
      global: ${ steps.changes.outputs.global }
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            bot:
            - "packages/bot/**"
            gateway:
            - "packages/gateway/**"
            rest:
            - "packages/rest/**"
            types:
            - "packages/types/**"
            utils:
            - "packages/utils/**"
            global:
            - ".github/workflows/release.yml"

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        package: ["bot", "gateway", "rest", "types", "utils"]
        run: [false]
        exclude:
          - package: bot
            run: ${{ needs.path-filter.outputs.bot || needs.path-filter.outputs.global }}
          - package: gateway
            run: ${{ needs.path-filter.outputs.gateway || needs.path-filter.outputs.global }}
          - package: rest
            run: ${{ needs.path-filter.outputs.rest || needs.path-filter.outputs.global }}
          - package: types
            run: ${{ needs.path-filter.outputs.types || needs.path-filter.outputs.global }}
          - package: utils
            run: ${{ needs.path-filter.outputs.utils || needs.path-filter.outputs.global }}
    needs: path-filter
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://npm.pkg.github.com"
          scope: "@discordeno"
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --immutable
      - name: Turbo Cache
        id: turbo-cache
        uses: actions/cache@v3
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-release-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-release-build-
      - name: build Package
        run: yarn release-build --cache-dir=".turbo"
      - name: Bump Package Version
        run: node ./scripts/bumpVersionByCommit.js ${{ matrix.package }}
      - run: npm publish
        working-directory: packages/${{ matrix.package }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
